[Desktop Entry]
Name=Blue-Sky-Custom
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=BlueSky-Dark
MetacityTheme=Material-Black-Frost-3.36
IconTheme=BlueSky-Dark
GtkColorScheme=fg_color:#4dfefd,bg_color:#052524,text_color:#00fffe,base_color:#1f3c41,selected_fg_color:#000000,selected_bg_color:#1d8a89,tooltip_fg_color:#4dfefd,tooltip_bg_color:#021215
CursorTheme=ModBlackmoon-SteelKing
CursorSize=32
NotificationTheme=coco
BackgroundImage=/usr/share/backgrounds/macaw.jpg
